### ISSUE TITLE
LWAP Stuns No Matter What

### ISSUE THREAD

**Issue by ParadoxSpace** [PolarisSS13/Polaris#1344]
Even if your armor stops the brunt of the attack, and even if your shield does it, the LWAP will stun you no matter what.

**Comment by Datraen** [comment]
Fixed via #1348

**Comment by Neerti** [comment]
Technically this is still broken, as other projectiles with certain properties bypass shields (when they shouldn't), which is the true cause of the bug.

**Comment by Anewbe** [comment]
Seems to be untrue on 9/29/16, closing
