### ISSUE TITLE
Flavour text is blanked out on attempting to edit

### ISSUE THREAD

**Issue by sabiram** [PolarisSS13/Polaris#512]
On click, the box pops up to allow you to edit, but the box is empty. Expected behavior would retain the previously entered text, like employment/medical records presently do.

**Comment by SinTwo** [comment]
Fixed! Except for the general field.

**Comment by Zuhayr** [comment]
Fixed or not fixed, Sin?

**Comment by EmperorJon** [comment]
I can confirm that this is not fixed. I'll take a look into it now actually.
